# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/scpd/cuLBM

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/scpd/cuLBM

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/scpd/cuLBM/CMakeFiles /home/scpd/cuLBM//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/scpd/cuLBM/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named LBM

# Build rule for target.
LBM: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LBM
.PHONY : LBM

# fast build rule for target.
LBM/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LBM.dir/build.make CMakeFiles/LBM.dir/build
.PHONY : LBM/fast

#=============================================================================
# Target rules for targets named Engine

# Build rule for target.
Engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Engine
.PHONY : Engine

# fast build rule for target.
Engine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/build
.PHONY : Engine/fast

src/common/Bitmap.o: src/common/Bitmap.cpp.o

.PHONY : src/common/Bitmap.o

# target to build an object file
src/common/Bitmap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/common/Bitmap.cpp.o
.PHONY : src/common/Bitmap.cpp.o

src/common/Bitmap.i: src/common/Bitmap.cpp.i

.PHONY : src/common/Bitmap.i

# target to preprocess a source file
src/common/Bitmap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/common/Bitmap.cpp.i
.PHONY : src/common/Bitmap.cpp.i

src/common/Bitmap.s: src/common/Bitmap.cpp.s

.PHONY : src/common/Bitmap.s

# target to generate assembly for a file
src/common/Bitmap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/common/Bitmap.cpp.s
.PHONY : src/common/Bitmap.cpp.s

src/common/Lattice.o: src/common/Lattice.cpp.o

.PHONY : src/common/Lattice.o

# target to build an object file
src/common/Lattice.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/common/Lattice.cpp.o
.PHONY : src/common/Lattice.cpp.o

src/common/Lattice.i: src/common/Lattice.cpp.i

.PHONY : src/common/Lattice.i

# target to preprocess a source file
src/common/Lattice.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/common/Lattice.cpp.i
.PHONY : src/common/Lattice.cpp.i

src/common/Lattice.s: src/common/Lattice.cpp.s

.PHONY : src/common/Lattice.s

# target to generate assembly for a file
src/common/Lattice.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/common/Lattice.cpp.s
.PHONY : src/common/Lattice.cpp.s

src/common/Parameters.o: src/common/Parameters.cpp.o

.PHONY : src/common/Parameters.o

# target to build an object file
src/common/Parameters.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/common/Parameters.cpp.o
.PHONY : src/common/Parameters.cpp.o

src/common/Parameters.i: src/common/Parameters.cpp.i

.PHONY : src/common/Parameters.i

# target to preprocess a source file
src/common/Parameters.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/common/Parameters.cpp.i
.PHONY : src/common/Parameters.cpp.i

src/common/Parameters.s: src/common/Parameters.cpp.s

.PHONY : src/common/Parameters.s

# target to generate assembly for a file
src/common/Parameters.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/common/Parameters.cpp.s
.PHONY : src/common/Parameters.cpp.s

src/cpu/CpuSolver.o: src/cpu/CpuSolver.cpp.o

.PHONY : src/cpu/CpuSolver.o

# target to build an object file
src/cpu/CpuSolver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/cpu/CpuSolver.cpp.o
.PHONY : src/cpu/CpuSolver.cpp.o

src/cpu/CpuSolver.i: src/cpu/CpuSolver.cpp.i

.PHONY : src/cpu/CpuSolver.i

# target to preprocess a source file
src/cpu/CpuSolver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/cpu/CpuSolver.cpp.i
.PHONY : src/cpu/CpuSolver.cpp.i

src/cpu/CpuSolver.s: src/cpu/CpuSolver.cpp.s

.PHONY : src/cpu/CpuSolver.s

# target to generate assembly for a file
src/cpu/CpuSolver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/cpu/CpuSolver.cpp.s
.PHONY : src/cpu/CpuSolver.cpp.s

src/gpu/GpuSolver.o: src/gpu/GpuSolver.cu.o

.PHONY : src/gpu/GpuSolver.o

# target to build an object file
src/gpu/GpuSolver.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/gpu/GpuSolver.cu.o
.PHONY : src/gpu/GpuSolver.cu.o

src/gpu/GpuSolver.i: src/gpu/GpuSolver.cu.i

.PHONY : src/gpu/GpuSolver.i

# target to preprocess a source file
src/gpu/GpuSolver.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/gpu/GpuSolver.cu.i
.PHONY : src/gpu/GpuSolver.cu.i

src/gpu/GpuSolver.s: src/gpu/GpuSolver.cu.s

.PHONY : src/gpu/GpuSolver.s

# target to generate assembly for a file
src/gpu/GpuSolver.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/gpu/GpuSolver.cu.s
.PHONY : src/gpu/GpuSolver.cu.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LBM.dir/build.make CMakeFiles/LBM.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LBM.dir/build.make CMakeFiles/LBM.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LBM.dir/build.make CMakeFiles/LBM.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Engine"
	@echo "... LBM"
	@echo "... src/common/Bitmap.o"
	@echo "... src/common/Bitmap.i"
	@echo "... src/common/Bitmap.s"
	@echo "... src/common/Lattice.o"
	@echo "... src/common/Lattice.i"
	@echo "... src/common/Lattice.s"
	@echo "... src/common/Parameters.o"
	@echo "... src/common/Parameters.i"
	@echo "... src/common/Parameters.s"
	@echo "... src/cpu/CpuSolver.o"
	@echo "... src/cpu/CpuSolver.i"
	@echo "... src/cpu/CpuSolver.s"
	@echo "... src/gpu/GpuSolver.o"
	@echo "... src/gpu/GpuSolver.i"
	@echo "... src/gpu/GpuSolver.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

